### ISSUE TITLE
Get error while install osm on new k3s 

### ISSUE THREAD

**Issue by caishu97** [flomesh-io/osm-edge#49]
**Bug description**:

**Affected area (please mark with X where applicable)**:
- Install                    [*]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Sidecar Control Plane      [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:
Follow installation guide, https://osm-edge-docs.flomesh.io/docs/getting_started/setup_osm/#在-kubernetes-上安装-osm-edge , osm should be installed. 

**Steps to reproduce the bug (as precisely as possible)**:
1. install a fresh new ubuntu2. 
2. install k3s by 'curl -sfL https://get.k3s.io | sh -'
3. install osm follow this guide :  https://osm-edge-docs.flomesh.io/docs/getting_started/setup_osm/#在-kubernetes-上安装-osm-edge

How was OSM installed?**:

**Anything else we need to know?**:
Error message : Error: unable to list meshes within the cluster: Could not list deployments Get "http://localhost:8080/apis/apps/v1/deployments?labelSelector=app%3Dosm-controller": dial tcp 127.0.0.1:8080: connect: connection refused

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`): ubuntu21, arm64 verison
- Kubernetes version (use `kubectl version`): k3s latest, Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8+k3s1", GitCommit:"53f2d4e7d80c09a7db1858e3f4e7ddfa13256c45", GitTreeState:"clean", BuildDate:"2022-06-27T21:49:50Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8+k3s1", GitCommit:"53f2d4e7d80c09a7db1858e3f4e7ddfa13256c45", GitTreeState:"clean", BuildDate:"2022-06-27T21:49:50Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/arm64"}

- Size of cluster (number of worker nodes in the cluster):1
- Others:

**Comment by keveinliu** [comment]
This issue comes with lack of `.kube/config` file, thus `osm` command invokes `http://localhost:8080` as Kubernetes API service endpoint. 
Particularly in K3s, the context stores in `/etc/rancher/k3s/k3s.yaml` rather than `.kube/config`. So the solution to this issue is to copy that file into your home directory, like this:
```
$ cp /etc/rancher/k3s/k3s.yaml  ~/.kube/config
```

**Note**:  If you already have a `.kube/config` in your home directory, please refer to the following Kubernetes official link to add a new cluster config. [configure-access-multiple-clusters](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/)

**Comment by caishu97** [comment]
It works : $ cp /etc/rancher/k3s/k3s.yaml  ~/.kube/config
